"""empty message

Revision ID: ffab4267a26e
Revises: 
Create Date: 2022-12-06 16:42:54.867275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffab4267a26e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ur_ls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('ur_ls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ur_ls_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ur_ls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ur_ls_name'))

    op.drop_table('ur_ls')
    # ### end Alembic commands ###
